name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-18.04
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run the tests
        run: ./.ci/test.sh
